[package]
name = "tokio-oplock"
version = "0.1.0"
edition = "2024"
description = "Safe async Windows oplock abstractions for Rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/amit-zimbalist/tokio-oplock"
keywords = ["windows", "oplock", "iocp", "async", "filesystem"]
categories = ["os::windows-apis", "asynchronous"]

[dependencies]
tokio = { version = "1", features = [
    "fs",
    "rt-multi-thread",
    "macros",
    "sync",
    "time",
    "signal",
] }

windows-sys = { version = "0.61", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_IO",
    "Win32_System_Ioctl",
] }
